### ISSUE TITLE
Vagrant up fails with mismatched checksum

### ISSUE THREAD

**Issue by tryggth** [flynn-archive/flynn-demo#17]
Vagrant up fails with mismatched checksum:

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Box 'flynn-precise64' was not found. Fetching box from specified URL f
or
the provider 'virtualbox'. Note that if the URL does not have
a box for this provider, you should interrupt Vagrant now and add
the box yourself. Otherwise Vagrant will attempt to download the
full box prior to discovering this error.
Downloading box from URL: https://s3.amazonaws.com/flynn/flynn-virtualbox-ubuntu
_12.04.3-amd64.box
Calculating and comparing box checksum...time remaining: 0:00:01)
The checksum of the dowloaded box did not match the expected
value. Please verify that you have the proper URL setup and that
you're downloading the proper file.

Expected: d222d515e83e0d8a547c55f9e5cbaec703fd414f0d761193d9fee1c6066504cf
Received: 5442243c66b0fa048bd5d1e8fa25b76254da3c53bfeb10582ca3d7a19afe5956

**Comment by tryggth** [comment]
This consistently happens for me (3 tries).

**Comment by titanous** [comment]
I'm 99% sure that's the correct hash:

``` text
$ curl -sI https://s3.amazonaws.com/flynn/flynn-virtualbox-ubuntu_12.04.3-amd64.box | grep ETag
ETag: "fcf5f76c6bf90e1e9304f1ea31efdff7"
$ md5 flynn-virtualbox-ubuntu_12.04.3-amd64.box
MD5 (flynn-virtualbox-ubuntu_12.04.3-amd64.box) = fcf5f76c6bf90e1e9304f1ea31efdff7
$ shasum -a 256 flynn-virtualbox-ubuntu_12.04.3-amd64.box
d222d515e83e0d8a547c55f9e5cbaec703fd414f0d761193d9fee1c6066504cf  flynn-virtualbox-ubuntu_12.04.3-amd64.box
```

**Comment by tryggth** [comment]
OK, I'll try it again. But if I get the same hash for the download...

**Comment by titanous** [comment]
Yeah, if it still doesn't work I'd just drop the hash from the Vagrantfile and hope for the best.

**Comment by tryggth** [comment]
Just tried again. vagrant up did a 1.5 hour download. And I ended up with exactly the same mis-matched hash on the downloaded file. That it did a long download suggests it wasn't using a locally cached image. I will try removing the hash value from the Vagrantfile as suggested, but it seems strange I would get exactly the same thing twice.
