### ISSUE TITLE
README.md instructions do not work

### ISSUE THREAD

**Issue by kangaroo** [flynn-archive/flynn-demo#18]
I checked out master/034b11ca29386b86615dea7dbe495287331d9f42, and did a vagrant up followed by make, but flynn failed to start with the following:

vagrant@packer-virtualbox:/vagrant$ make
bin/forego start
forego     | starting etcd on port 5000
forego     | starting discoverd on port 5100
forego     | starting gitreceive on port 5200
forego     | starting shelf on port 5300
forego     | starting strowger on port 5400
forego     | starting host on port 5500
forego     | starting controller on port 5600
etcd       | [etcd] Feb  8 06:40:15.341 WARNING   | Using the directory packer-virtualbox.etcd as the etcd curation directory because a directory was not specified. 
etcd       | [etcd] Feb  8 06:40:15.368 INFO      | etcd server [name packer-virtualbox, listen on :4001, advertised url http://127.0.0.1:4001]
discoverd  | 2014/02/08 06:40:15 Starting server on :1111...
etcd       | [etcd] Feb  8 06:40:15.425 INFO      | URLs:  / packer-virtualbox (http://127.0.0.1:7001)
etcd       | [etcd] Feb  8 06:40:15.432 WARNING   | the entire cluster is down! this peer will restart the cluster.
etcd       | [etcd] Feb  8 06:40:15.432 INFO      | raft server [name packer-virtualbox, listen on :7001, advertised url http://127.0.0.1:7001]
discoverd  | 2014/02/08 06:40:16 Register: shelf 10.0.2.15:8888 map[]
discoverd  | 2014/02/08 06:40:16 Register: flynn-strowger-rpc :1115 map[]
shelf      | 2014/02/08 06:40:16 Shelf serving files on 8888 from /vagrant/storage
host       | now=2014-02-08T06:40:17+0000 app=lorne at=start
discoverd  | 2014/02/08 06:40:17 Register: flynn-host 10.0.2.15:1113 map[id:]
discoverd  | 2014/02/08 06:40:17 Subscribe: flynn-host
discoverd  | 2014/02/08 06:40:17 Subscribe: flynn-host
host       | now=2014-02-08T06:40:17+0000 app=lorne fn=main at=sampi_connected
host       | now=2014-02-08T06:40:17+0000 app=lorne fn=main at=host_registered
forego     | shutting down
forego     | sending SIGTERM to etcd
forego     | sending SIGTERM to discoverd
forego     | sending SIGTERM to gitreceive
forego     | sending SIGTERM to shelf
forego     | sending SIGTERM to strowger
forego     | sending SIGTERM to controller
shelf      | 2014/02/08 06:40:17 rpc: client protocol error: read tcp 127.0.0.1:1111: connection reset by peer

**Comment by titanous** [comment]
Fixed by a28cba39cc5b04d12ecfda4f01e7b7958821d075 / #19.
