### ISSUE TITLE
/tmp/keys/vagrant disappears after rebooting vagrant box

### ISSUE THREAD

**Issue by kimh** [flynn-archive/flynn-demo#20]
Since you are saving ssh pub key needed by gitreceive under /tmp directory, the key will disappear when you reboot the machine.

This will lead `Permission denied (publickey)` error when you try to push coes after rebooting because gitreceive can't load the key.

I don't know the expectation of gitreceive, but can't we save the key in different place?

**Comment by titanous** [comment]
Yeah, we're going to switch to using a controller API for key lookup very soon.

**Comment by kimh** [comment]
So, should I close this one? I think it is good to leave this info somewhere. It is not that easy to find out what's going on if you don't know how gitreceive works.

**Comment by titanous** [comment]
Feel free to leave it, I'll close when it's fixed.
