### ISSUE TITLE
Use vagrant multi-machine for clustering

### ISSUE THREAD

**Issue by stephen-fanfair** [flynn-archive/flynn-demo#22]
It might be helpful for the Vagrantfile to be able to generate a cluster of vagrant boxes to test distribution across machines. Maybe put it behind an env variable? I'll look at it a bit tonight.

**Comment by lmars** [comment]
@stephen-fanfair there is an example of this in flynn-grid:

https://github.com/flynn/flynn-grid/blob/master/cluster-test/Vagrantfile

**Comment by stephen-fanfair** [comment]
Awesome! Just what I needed. :D
