### ISSUE TITLE
shelf can't boot from make command

### ISSUE THREAD

**Issue by chinamerp** [flynn-archive/flynn-demo#23]
at Procfile the command get an error:

shelf      | flag provided but not defined: -s

reason is the "-s" 
shelf: sleep 1 && bin/sdutil exec -h 10.0.2.15 -s shelf:8888 bin/shelf -p 8888 /vagrant/storage

**Comment by titanous** [comment]
Sounds like your sdutil is outdated, try running `go get -v -u github.com/flynn/sdutil`.

**Comment by chinamerp** [comment]
it worked when had updated the sudtil.
but got a new error. the logs following:
vagrant@packer-virtualbox:/vagrant$ bin/forego start
forego     | starting etcd on port 5000
forego     | starting discoverd on port 5100
forego     | starting gitreceive on port 5200
forego     | starting shelf on port 5300
forego     | starting strowger on port 5400
forego     | starting host on port 5500
forego     | starting controller on port 5600
discoverd  | 2014/03/19 02:16:45 Starting server on :1111...
etcd       | [etcd] Mar 19 02:16:45.191 WARNING   | Using the directory packer-virtualbox.etcd as the etcd curation directory because a directory was not specified. 
etcd       | [etcd] Mar 19 02:16:45.202 INFO      | etcd server [name packer-virtualbox, listen on :4001, advertised url http://127.0.0.1:4001]
shelf      | 2014/03/19 02:16:46 Shelf serving files on 8888 from /vagrant/storage
host       | now=2014-03-19T02:16:47+0000 app=lorne at=start
discoverd  | 2014/03/19 02:16:47 Register: error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
discoverd  | 2014/03/19 02:16:47 Register: error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
strowger   | 2014/03/19 02:16:47 discover: register failed: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
forego     | shutting down
forego     | sending SIGTERM to etcd
forego     | sending SIGTERM to discoverd
forego     | sending SIGTERM to gitreceive
forego     | sending SIGTERM to shelf
forego     | sending SIGTERM to host
forego     | sending SIGTERM to controller

**Comment by titanous** [comment]
@chinamerp check out #16.

**Comment by chinamerp** [comment]
fixed by adding -f to  etcd
