### ISSUE TITLE
Packer and Digital Ocean

### ISSUE THREAD

**Issue by jpscharf** [flynn-archive/flynn-demo#29]
When attempting to run `packer build -only digitalocean cloud.json`, it fails:

```
==> digitalocean: Creating temporary ssh key for droplet...
==> digitalocean: Creating droplet...
==> digitalocean: Error creating droplet: Received error from DigitalOcean (404): You specified an invalid image for Droplet creation.
==> digitalocean: Deleting temporary ssh key...
Build 'digitalocean' errored: Error creating droplet: Received error from DigitalOcean (404): You specified an invalid image for Droplet creation.

==> Some builds didn't complete successfully and had errors:
--> digitalocean: Error creating droplet: Received error from DigitalOcean (404): You specified an invalid image for Droplet creation.

==> Builds finished but no artifacts were created.
```

**Comment by titanous** [comment]
Looks like there isn't a source image specified in the template. @progrium was the one who wrote it and currently works at DO, perhaps he can update it?

**Comment by progrium** [comment]
Yeah, I don't think I finished the digitalocean one. :\

On Wed, Apr 23, 2014 at 7:08 PM, Jonathan Rudenberg <
notifications@github.com> wrote:

> Looks like there isn't a source image specified in the template. @progriumhttps://github.com/progriumwas the one that wrote it and currently works at DO, perhaps he can update
> it?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/flynn-demo/issues/29#issuecomment-41229727
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by titanous** [comment]
@jpscharf I've deleted it for now so that it doesn't cause confusion. If someone wants to make a pull request for a complete template, I'll merge it.
