### ISSUE TITLE
Kernel 3.8 on Vagrant Box

### ISSUE THREAD

**Issue by jayd3e** [flynn-archive/flynn-demo#32]
Due to a bug in docker, running containers are occasionally unkillable.  This can be solved by updating the kernel to 3.8 on the base vagrant image.  Directions are found here http://docs.docker.io/installation/ubuntulinux/.

**Comment by titanous** [comment]
In the flynn-base image:

``` text
$ uname -r
3.11.0-19-generic
```

**Comment by jayd3e** [comment]
Hmmm maybe the bug doesn't apply to 3.8 as I thought.  All I know is that I recently encountered the bug where docker processes become unkillable on the flynn-demo box.  This is solved by updating the kernel.  If you've never seen this behavior before and have been using flynn-demo for a while, then hold off on this and I'll just see if it happens again.

**Comment by titanous** [comment]
Did you restart the VM? Are you sure that the processes were actually running?

**Comment by titanous** [comment]
Also, if you installed 3.8 and actually booted into it, you downgraded the kernel.

**Comment by jayd3e** [comment]
So I mistakenly threw out the version 3.8 apparently, as I saw it on the docker website.  It appears that that install script(https://get.docker.io/ubuntu/) does the same thing that flynn-demo does atm, but also adds the docker repository.  So it pulls the latest version of docker(maybe not desirable).

**Comment by jayd3e** [comment]
But yeah close if you don't think it's important.

**Comment by titanous** [comment]
We also pull the latest version of docker: https://github.com/flynn/flynn-demo/blob/6a64747046f7e93929c26cacd258b84cae633c55/Vagrantfile#L22-L23

**Comment by jayd3e** [comment]
kk cool
