### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by arthurzenika** [flynn-archive/flynn-demo#39]
using the flynn-demo with nodjs-flynn-example I get the following error:

```
nodejs-flynn-example$ git push flynn master
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

How do I add my key ? Should I use a temporary generated private key ? Where do I find it ?

**Comment by titanous** [comment]
If you already have an SSH key `flynn key-add` should do the trick. You can also pass a path to a public key file if you want to use a specific key.

**Comment by arthurzenika** [comment]
Sorry, I missed the flynn key-add step.
