### ISSUE TITLE
Box fails to unpackage on Vagrant 1.6.2 / OSX (xz utility required)

### ISSUE THREAD

**Issue by chriskilding** [flynn-archive/flynn-demo#40]
When I run 'vagrant up' in this project (using Vagrant 1.6.2 / OSX Mavericks), Vagrant can't parse the box once downloaded and produces the following error:

```
default: Downloading: https://github.com/flynn/flynn-demo/releases/download/v0.4.0/flynn-base_virtualbox.box
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar: Error opening archive: Can't initialize filter; unable to run program "xz -d -qq"
```

On closer inspection it is complaining because the `xz` utility is not installed by default in Mavericks, so users on this platform should `brew install xz` first. Alternatively, should xz be added (or perhaps removed if not really needed?) as a dependency of flynn-demo?

Every other pre-packaged Vagrant box I have used works fine, leading me to think this is something specific to flynn-demo's box rather than a general Vagrant bug. But I could be mistaken.

**Comment by titanous** [comment]
How did you install Vagrant?

**Comment by chriskilding** [comment]
Vagrant 1.6.2 installed from .pkg

**Comment by titanous** [comment]
K, testing locally with xz not installed.

**Comment by titanous** [comment]
Replicated. I think this is a Vagrant bug, I'm pretty sure the omnibus installers are supposed to include all dependencies. I will file a bug and add a note to the README.

**Comment by titanous** [comment]
After further research, it looks like Vagrant might only support 7-zip formatted LZMA compression. I'm testing now.

**Comment by srobertson** [comment]
If it helps... I can confirm this bug

**Comment by titanous** [comment]
A box compressed with `bsdtar --lzma` fails with a similar message:

``` text
bsdtar: Error opening archive: Can't initialize filter; unable to run program "lzma -d -qq"
```

Still testing...

**Comment by titanous** [comment]
A box compressed with `7z` fails with this error:

``` text
x packer_virtualbox-iso_virtualbox.box: LZMA codec is unsupported
bsdtar: Error exit delayed from previous errors.
```

Filing an upstream issue now.

**Comment by titanous** [comment]
Upstream issue: mitchellh/vagrant#3893

**Comment by srobertson** [comment]
On mac this fixed the issue

``` bash
$  brew install xz
```

**Comment by titanous** [comment]
@srobertson yep, I've noted that in the README.
