### ISSUE TITLE
Add a convenient alias domain like 'flynnapp.com'

### ISSUE THREAD

**Issue by chriskilding** [flynn-archive/flynn-demo#41]
It would be convenient if we were able to reference the flynn vagrant box with a nice domain name rather than 'localhost:some port' or IP addresses. My suggestion would be 'flynnapp.com' as it's kinda like 'herokuapp.com'.

Once this is in place you could have per-app subdomains, like 'myapp.flynnapp.com'.

**Comment by titanous** [comment]
We already own flynnhub.com, so something like local.flynnhub.com is an option.

**Comment by chriskilding** [comment]
If there were per-app subdomains (generated from the git remote name perhaps), could the `flynn route-add-http` step be run automatically with the app name inserted? (This may be an issue for flynn core rather than demo)

**Comment by titanous** [comment]
Yep, that's already partially implemented. The last part is a name generator.

**Comment by titanous** [comment]
We just bought localflynn.com for this feature.

**Comment by titanous** [comment]
*.localflynn.com DNS now points at 127.0.0.1
