### ISSUE TITLE
Rails web app not available after being pushed to demo box and started

### ISSUE THREAD

**Issue by chriskilding** [flynn-archive/flynn-demo#42]
Using the Flynn vagrant demo box, I:
- push a Rails app, and the Heroku build pack runs successfully
- add a route alias localhost:8080
- `flynn scale web=1`
- add DATABASE_URL as an environment variable
- `flynn run rake db:migrate`, which I know has completed because it doesn't throw a database connection error, although it does complain about stdin not being in gzip format

But when I try to access localhost:8080, I get 'Service unavailable' errors, and on occasion 'Bad gateway' errors. Running `flynn log` on the web process yields nothing. What am I (or Flynn) doing wrong?

**Comment by titanous** [comment]
DATABASE_URL is not currently supported.

The stdin not gzip error is actually a fatal error that hasn't been tracked down yet.

**Comment by chriskilding** [comment]
FWIW when I provide a DATABASE_URL with the wrong username/password, I get a postgresql exception that the username/password is incorrect, as I would do when running Rails in any other environment. So it does work in at least some ways.
