### ISSUE TITLE
window 7 64bit  error to add coreos box 

### ISSUE THREAD

**Issue by simapple** [flynn-archive/flynn-demo#46]
E:>vagrant box add coreos-alpha coreos_production_vagrant_494_5_0.box -f
==> box: Adding box 'coreos-alpha' (v0) for provider:
    box: Downloading: file://E:/coreos_production_vagrant_494_5_0.box
    box: Progress: 100% (Rate: 369M/s, Estimated time remaining: --:--:--)
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

version 1.7.2

**Comment by titanous** [comment]
This is the wrong repo. Try https://github.com/coreos/coreos-vagrant/issues
