### ISSUE TITLE
Build our own Vagrant box with Packer

### ISSUE THREAD

**Issue by titanous** [flynn-archive/flynn-demo#7]
Since we don't need Chef/Puppet/Ruby, etc.
- Ubuntu 12.04.3 amd64
- Kernel 3.8
- AUFS kernel module
- memory cgroup and swap accounting [enabled](http://docs.docker.io/en/latest/installation/kernel/#memory-and-swap-accounting-on-debian-ubuntu)
- `make`, `mercurial`, `curl`, `git`, `vim` (anything else?)
- VirtualBox Guest additions compatible with 4.2 and 4.3

Starting point: https://github.com/mitchellh/packer-ubuntu-12.04-docker

**Comment by marceldegraaf** [comment]
This is a replacement for the Phusion box?

**Comment by titanous** [comment]
Yeah, it will be. The Phusion box is a great start, but I'd like to slim down the footprint.

**Comment by marceldegraaf** [comment]
Cool! I don't have any experience with Packer, so perhaps someone else can have a stab at this? I could dive into it if no Packer-savants show up :smile:

**Comment by titanous** [comment]
I went ahead and did this: https://github.com/flynn/packer-ubuntu-12.04-docker
